{"name": "test_oldpwd_error_zj", "status": "broken", "statusDetails": {"message": "AttributeError: 'Login' object has no attribute 'gp_login'", "trace": "driver_fixture = <appium.webdriver.webdriver.WebDriver (session=\"0e7b83d5-90bd-4243-ba0f-6351e0c81c1e\")>\n\n    @pytest.fixture(scope='session',autouse=False)\n    def gp_login_fixture(driver_fixture):\n        csv_file=BASE_DIR + '\\datas\\login.csv'\n        print(\"csv_file:%s\"%csv_file)\n        driver=driver_fixture\n        com=Common(driver)\n        data=com.get_csv_data(csv_file,2)\n        time.sleep(2)\n        trd=First(driver)\n        trd.to_login()\n        logn=Login(driver)\n>       logn.gp_login(data[0],data[1])\nE       AttributeError: 'Login' object has no attribute 'gp_login'\n\nconftest.py:54: AttributeError"}, "start": 1652795334272, "stop": 1652795334272, "uuid": "f105c0a9-75fb-472f-ab60-3c6027b58fb0", "historyId": "47af0771051d1d170be8e0553e7624af", "testCaseId": "1256a8d14c38081eed87c61121bf62ad", "fullName": "testGp.test_new_Gp.TestGp#test_oldpwd_error_zj", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('back_fixture')"}, {"name": "parentSuite", "value": "testGp"}, {"name": "suite", "value": "test_new_Gp"}, {"name": "subSuite", "value": "TestGp"}, {"name": "host", "value": "Win102021AVUCSJ"}, {"name": "thread", "value": "10404-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testGp.test_new_Gp"}]}