{"uuid": "6b62d0c7-3c68-4647-9bd7-46806ffd2c40", "children": ["16a6747c-19c7-41f4-9dfb-178a250caf83"], "befores": [{"name": "setup_fixture", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: 'GET /screenshot' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details\n\n", "trace": "  File \"D:\\xiaxy\\python\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\xiaxy\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\xiaxy\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 932, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"D:\\xiaxy\\automation_test2022.4.22\\testcases\\testFirstPage\\test_Qfirst_page.py\", line 16, in setup_fixture\n    tradehome.to_first_page()\n  File \"D:\\xiaxy\\automation_test2022.4.22\\businessPage\\trade_first_page.py\", line 34, in to_first_page\n    self.get_clickable_element(self.first_page,\"首页\")\n  File \"D:\\xiaxy\\automation_test2022.4.22\\common\\common_fun.py\", line 275, in get_clickable_element\n    self.error_save_screenshot(desc)\n  File \"D:\\xiaxy\\automation_test2022.4.22\\common\\common_fun.py\", line 258, in error_save_screenshot\n    raise e\n  File \"D:\\xiaxy\\automation_test2022.4.22\\common\\common_fun.py\", line 254, in error_save_screenshot\n    self.driver.save_screenshot(file_path)\n  File \"D:\\xiaxy\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 1055, in save_screenshot\n    return self.get_screenshot_as_file(filename)\n  File \"D:\\xiaxy\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 1032, in get_screenshot_as_file\n    png = self.get_screenshot_as_png()\n  File \"D:\\xiaxy\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 1064, in get_screenshot_as_png\n    return base64.b64decode(self.get_screenshot_as_base64().encode('ascii'))\n  File \"D:\\xiaxy\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 1074, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)['value']\n  File \"D:\\xiaxy\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\xiaxy\\python\\lib\\site-packages\\appium\\webdriver\\errorhandler.py\", line 31, in check_response\n    raise wde\n  File \"D:\\xiaxy\\python\\lib\\site-packages\\appium\\webdriver\\errorhandler.py\", line 26, in check_response\n    super().check_response(response)\n  File \"D:\\xiaxy\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1652712710782, "stop": 1652712710789}], "start": 1652712710782, "stop": 1652712710908}